# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quick Maths' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quick Maths
  pod 'Alamofire'

  target 'Quick MathsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Quick MathsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
